var opendoc = false;

/** GLOBAL Properties related to the application Which needs to be changed on client req **/
var global = {
	"preference": "",
	"componetIDPrefix": "BVZ",
	"versionLabel": "4.5.0",
	"dashboardJSONForPreview": "",
	"versionDetail": "@@versionDetail",
	"buildDate": "@@buildDate"
};
global.src_url_designhome = {};
global.src_url_designhome.prodJS = [
	"build-config/build/ui-codemirror.min.js?v=@@timestamp",
	"build-config/build/bvzNumberSpinner.min.js?v=@@timestamp",
	"build-config/build/designer.ctrl.min.js?v=@@timestamp",
	"build-config/build/designer.fact.min.js?v=@@timestamp",
	"build-config/build/designer.dir.min.js?v=@@timestamp"
];
global.src_url_designhome.devJS = [
	"./resources/plugins/angularjs/ui-codemirror.js?v=@@timestamp",
	"./resources/plugins/bvzPlugins/js/bvzNumberSpinner.js?v=@@timestamp",
	"./common/app.js?v=@@timestamp",
	"./directives/DesignerDirective.js?v=@@timestamp",
	"./directives/DataSourceDirective.js?v=@@timestamp",
	"./directives/PropertyDirective.js?v=@@timestamp",
	"./directives/angular-drag-and-drop-lists.js?v=@@timestamp",
	"./factories/ServiceFactory.js?v=@@timestamp",
	"./factories/DesignerFactory.js?v=@@timestamp",
	"./controllers/DatasetController.js?v=@@timestamp",
	"./controllers/DesignerController.js?v=@@timestamp",
	"./controllers/MainMenuController.js?v=@@timestamp",
	"./controllers/DesignerPropertyController.js?v=@@timestamp",
	"./controllers/DashboardDesignerController.js?v=@@timestamp",
	"./controllers/WidgetController.js?v=@@timestamp",
	"./controllers/DPController.js?v=@@timestamp",
	"./controllers/PropertyController.js?v=@@timestamp",
	"./controllers/UserScriptController.js?v=@@timestamp",
	"./controllers/ComponentAttributeController.js?v=@@timestamp",
	"./controllers/ObjectBrowserController.js?v=@@timestamp",
	"./controllers/FileExplorerController.js?v=@@timestamp",
	"./controllers/HelpController.js?v=@@timestamp"
];

global.src_url_designhome.prodCSS = [
	"build-config/build/bvzNumberSpinner.min.css?v=@@timestamp",
	"build-config/build/designer.min.css?v=@@timestamp"
];
global.src_url_designhome.devCSS = [
	"resources/css/help.css?v=@@timestamp",
	"resources/css/Designer.css?v=@@timestamp",
	"resources/plugins/bvzPlugins/css/bvzNumberSpinner.css?v=@@timestamp"
];

global.src_url_importcomponents = {};
global.src_url_importcomponents.parent_prodJS = [
	"../charting/build-config/build/bizviz.charting/chartingBase.min.js?v=@@timestamp",
	"../charting/build-config/build/bizviz.framework/chartingFramework.min.js?v=@@timestamp"
];
global.src_url_importcomponents.prodJS = [
	"../charting/build-config/build/bizviz.charting/components/buttons/ExportPlugin.min.js?v=@@timestamp",
	"../charting/build-config/build/bizviz.charting/chartingComponents.min.js?v=@@timestamp",
];
global.src_url_importcomponents.parent_devJS = [
	"../charting/src/bizviz.charting/Widget.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/Chart.js?v=@@timestamp",

	"../charting/src/bizviz.charting/components/buttons/ExportPlugin.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/DataGrid.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/Filter.js?v=@@timestamp",

	"../charting/src/bizviz.framework/Parser.js?v=@@timestamp",
	"../charting/src/bizviz.framework/DataManager.js?v=@@timestamp",
	"../charting/src/bizviz.framework/ServiceManager.js?v=@@timestamp",
	"../charting/src/bizviz.framework/GlobalVariableController.js?v=@@timestamp",
	"../charting/src/bizviz.framework/RendererController.js?v=@@timestamp",
	"../charting/src/bizviz.framework/FrameworkUtil.js?v=@@timestamp",
	"../charting/src/bizviz.framework/FrameworkController.js?v=@@timestamp"
]

global.src_url_importcomponents.devJS = [
	"../charting/src/bizviz.charting/components/buttons/ExportToPPTButton.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/buttons/FilterSaver.js?v=@@timestamp",

	"../charting/src/bizviz.charting/components/charts/AreaChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/BarChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/BenchmarkAnalysisChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/BubbleChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/BoxPlotChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/CandleStickChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/ChevronChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/CircumplexChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/ColumnStackChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/CustomChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/WidgetChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/DecompositionChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/DecisionTreeChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/GroupBarChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/GroupColumnChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/HeatMapChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/HistogramChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/InvertedFunnelChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/LineChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/KnowledgeGraphChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/KPITile.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/MitoPlotChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/MixedChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/PieChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/ProgressChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/ProjectTimelineChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/PyramidChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/ScatteredPlotChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/SentimentPlotChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/SimpleFunnelChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/SparkLineChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/SpiderChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/SankeyChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/TimelineChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/TreeMapChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/TrellisChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/WaterfallChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/WordCloudChart.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/charts/NewWordCloudChart.js?v=@@timestamp",

	"../charting/src/bizviz.charting/components/maps/WorldMapChart.js?v=@@timestamp",

	"../charting/src/bizviz.charting/components/datagrids/DynamicDataGrid.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/datagrids/SimpleDataGrid.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/datagrids/PagingDataGrid.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/datagrids/TreeGrid.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/datagrids/JExcelDataGrid.js?v=@@timestamp",

	"../charting/src/bizviz.charting/components/filters/CheckboxFilter.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/filters/ComboFilter.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/filters/HierarchicalCombo.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/filters/ListFilter.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/filters/RadioFilter.js?v=@@timestamp",

	"../charting/src/bizviz.charting/components/container/Rectangle.js?v=@@timestamp",

	"../charting/src/bizviz.charting/components/singleValuedComponent/Bullet.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/DataSearch.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/DatePicker.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/Gauge.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/GuidedTour.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/HSlider.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/ImageComponent.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/InfoButton.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/Label.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/Legend.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/NumericStepper.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/SemiGauge.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/SVGImage.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/SVGShape.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/TextBox.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/InputBox.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/Trend.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/UrlButton.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/InputButton.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/TabComponent.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/VSlider.js?v=@@timestamp",
	"../charting/src/bizviz.charting/components/singleValuedComponent/FilterChips.js?v=@@timestamp",
];

var dGlobals = {};
dGlobals.src_url_charts = {};
/**  Source URLS of components DEVELOPMENT **/
dGlobals.src_url_charts.devJS = {
	AreaChart : "src/bizviz.charting/components/charts/AreaChart.js?v=@@timestamp",
	BarChart : "src/bizviz.charting/components/charts/BarChart.js?v=@@timestamp",
	BenchmarkAnalysisChart : "src/bizviz.charting/components/charts/BenchmarkAnalysisChart.js?v=@@timestamp",
	ChevronChart : "src/bizviz.charting/components/charts/ChevronChart.js?v=@@timestamp",
	BoxPlotChart : "src/bizviz.charting/components/charts/BoxPlotChart.js?v=@@timestamp",
	BubbleChart : "src/bizviz.charting/components/charts/BubbleChart.js?v=@@timestamp",
	CandleStickChart : "src/bizviz.charting/components/charts/CandleStickChart.js?v=@@timestamp",
	ChevronChart : "src/bizviz.charting/components/charts/ChevronChart.js?v=@@timestamp",
	CircumplexChart : "src/bizviz.charting/components/charts/CircumplexChart.js?v=@@timestamp",
	ColumnStackChart : "src/bizviz.charting/components/charts/ColumnStackChart.js?v=@@timestamp",
	CustomChart : "src/bizviz.charting/components/charts/CustomChart.js?v=@@timestamp",
	WidgetChart : "src/bizviz.charting/components/charts/WidgetChart.js?v=@@timestamp",
	DecisionTreeChart:"src/bizviz.charting/components/charts/DecisionTreeChart.js?v=@@timestamp",
	DecompositionChart:"src/bizviz.charting/components/charts/DecompositionChart.js?v=@@timestamp",
	GroupBarChart : "src/bizviz.charting/components/charts/GroupBarChart.js?v=@@timestamp",
	GroupColumnChart : "src/bizviz.charting/components/charts/GroupColumnChart.js?v=@@timestamp",
	HeatMapChart : "src/bizviz.charting/components/charts/HeatMapChart.js?v=@@timestamp",
	HistogramChart : "src/bizviz.charting/components/charts/HistogramChart.js?v=@@timestamp",
	KnowledgeGraphChart : "src/bizviz.charting/components/charts/KnowledgeGraphChart.js?v=@@timestamp",
	KPITile : "src/bizviz.charting/components/charts/KPITile.js?v=@@timestamp",
	LineChart : "src/bizviz.charting/components/charts/LineChart.js?v=@@timestamp",
	MitoPlotChart : "src/bizviz.charting/components/charts/MitoPlotChart.js?v=@@timestamp",
	MixedChart : "src/bizviz.charting/components/charts/MixedChart.js?v=@@timestamp",
	PieChart : "src/bizviz.charting/components/charts/PieChart.js?v=@@timestamp",
	ProgressChart : "src/bizviz.charting/components/charts/ProgressChart.js?v=@@timestamp",
	ProjectTimelineChart : "src/bizviz.charting/components/charts/ProjectTimelineChart.js?v=@@timestamp",
	ScatteredPlotChart : "src/bizviz.charting/components/charts/ScatteredPlotChart.js?v=@@timestamp",
	SentimentPlotChart : "src/bizviz.charting/components/charts/SentimentPlotChart.js?v=@@timestamp",
	SparkLineChart : "src/bizviz.charting/components/charts/SparkLineChart.js?v=@@timestamp",
	SpiderChart : "src/bizviz.charting/components/charts/SpiderChart.js?v=@@timestamp",
	SankeyChart : "src/bizviz.charting/components/charts/SankeyChart.js?v=@@timestamp",
	TimelineChart : "src/bizviz.charting/components/charts/TimelineChart.js?v=@@timestamp",
	TreeMapChart : "src/bizviz.charting/components/charts/TreeMapChart.js?v=@@timestamp",
	TrellisChart : "src/bizviz.charting/components/charts/TrellisChart.js?v=@@timestamp",
	WordCloudChart : "src/bizviz.charting/components/charts/WordCloudChart.js?v=@@timestamp",
	NewWordCloudChart : "src/bizviz.charting/components/charts/NewWordCloudChart.js?v=@@timestamp",
	WaterfallChart : "src/bizviz.charting/components/charts/WaterfallChart.js?v=@@timestamp",
	WorldMapChart : "src/bizviz.charting/components/maps/WorldMapChart.js?v=@@timestamp",

	SimpleFunnelChart : "src/bizviz.charting/components/charts/SimpleFunnelChart.js?v=@@timestamp",
	InvertedFunnelChart : "src/bizviz.charting/components/charts/InvertedFunnelChart.js?v=@@timestamp",
	PyramidChart : "src/bizviz.charting/components/charts/PyramidChart.js?v=@@timestamp",

	Rectangle : "src/bizviz.charting/components/container/Rectangle.js?v=@@timestamp",

	DynamicDataGrid : "src/bizviz.charting/components/datagrids/DynamicDataGrid.js?v=@@timestamp",
	SimpleDataGrid : "src/bizviz.charting/components/datagrids/SimpleDataGrid.js?v=@@timestamp",
	PagingDataGrid : "src/bizviz.charting/components/datagrids/PagingDataGrid.js?v=@@timestamp",
	TreeGrid : "src/bizviz.charting/components/datagrids/TreeGrid.js?v=@@timestamp",
	ScoreCard : "src/bizviz.charting/components/datagrids/TreeGrid.js?v=@@timestamp",
	JExcelDataGrid : "src/bizviz.charting/components/datagrids/JExcelDataGrid.js?v=@@timestamp",

	CheckboxFilter : "src/bizviz.charting/components/filters/CheckboxFilter.js?v=@@timestamp",
	ComboFilter : "src/bizviz.charting/components/filters/ComboFilter.js?v=@@timestamp",
	HierarchicalCombo : "src/bizviz.charting/components/filters/HierarchicalCombo.js?v=@@timestamp",
	ListFilter : "src/bizviz.charting/components/filters/ListFilter.js?v=@@timestamp",
	RadioFilter : "src/bizviz.charting/components/filters/RadioFilter.js?v=@@timestamp",

	ExportToPPTButton :"src/bizviz.charting/components/buttons/ExportToPPTButton.js?v=@@timestamp",
	FilterSaver :"src/bizviz.charting/components/buttons/FilterSaver.js?v=@@timestamp",
	Bullet : "src/bizviz.charting/components/singleValuedComponent/Bullet.js?v=@@timestamp",
	DataSearch : "src/bizviz.charting/components/singleValuedComponent/DataSearch.js?v=@@timestamp",
	DatePicker : "src/bizviz.charting/components/singleValuedComponent/DatePicker.js?v=@@timestamp",
	Gauge : "src/bizviz.charting/components/singleValuedComponent/Gauge.js?v=@@timestamp",
	GuidedTour : "src/bizviz.charting/components/singleValuedComponent/GuidedTour.js?v=@@timestamp",
	SemiGauge : "src/bizviz.charting/components/singleValuedComponent/SemiGauge.js?v=@@timestamp",
	HSlider : "src/bizviz.charting/components/singleValuedComponent/HSlider.js?v=@@timestamp",
	ImageComponent : "src/bizviz.charting/components/singleValuedComponent/ImageComponent.js?v=@@timestamp",
	InfoButton : "src/bizviz.charting/components/singleValuedComponent/InfoButton.js?v=@@timestamp",
	Label : "src/bizviz.charting/components/singleValuedComponent/Label.js?v=@@timestamp",
	Legend : "src/bizviz.charting/components/singleValuedComponent/Legend.js?v=@@timestamp",
	NumericStepper : "src/bizviz.charting/components/singleValuedComponent/NumericStepper.js?v=@@timestamp",
	SVGImage : "src/bizviz.charting/components/singleValuedComponent/SVGImage.js?v=@@timestamp",
	SVGShape : "src/bizviz.charting/components/singleValuedComponent/SVGShape.js?v=@@timestamp",
	TextBox : "src/bizviz.charting/components/singleValuedComponent/TextBox.js?v=@@timestamp",
	InputBox : "src/bizviz.charting/components/singleValuedComponent/InputBox.js?v=@@timestamp",
	Trend : "src/bizviz.charting/components/singleValuedComponent/Trend.js?v=@@timestamp",
	UrlButton : "src/bizviz.charting/components/singleValuedComponent/UrlButton.js?v=@@timestamp",
	InputButton : "src/bizviz.charting/components/singleValuedComponent/InputButton.js?v=@@timestamp",
	TabComponent : "src/bizviz.charting/components/singleValuedComponent/TabComponent.js?v=@@timestamp",
	VSlider : "src/bizviz.charting/components/singleValuedComponent/VSlider.js?v=@@timestamp",
	FilterChips : "src/bizviz.charting/components/singleValuedComponent/FilterChips.js?v=@@timestamp"
};
/**  Source URLS of components PRODUCTION **/
dGlobals.src_url_charts.prodJS = {
	AreaChart : "build-config/build/bizviz.charting/components/charts/AreaChart.min.js?v=@@timestamp",
	BarChart : "build-config/build/bizviz.charting/components/charts/BarChart.min.js?v=@@timestamp",
	BenchmarkAnalysisChart : "build-config/build/bizviz.charting/components/charts/BenchmarkAnalysisChart.min.js?v=@@timestamp",
	BoxPlotChart : "build-config/build/bizviz.charting/components/charts/BoxPlotChart.min.js?v=@@timestamp",
	BubbleChart : "build-config/build/bizviz.charting/components/charts/BubbleChart.min.js?v=@@timestamp",
	CandleStickChart : "build-config/build/bizviz.charting/components/charts/CandleStickChart.min.js?v=@@timestamp",
	ChevronChart : "build-config/build/bizviz.charting/components/charts/ChevronChart.min.js?v=@@timestamp",
	CircumplexChart : "build-config/build/bizviz.charting/components/charts/CircumplexChart.min.js?v=@@timestamp",
	ColumnStackChart : "build-config/build/bizviz.charting/components/charts/ColumnStackChart.min.js?v=@@timestamp",
	CustomChart : "build-config/build/bizviz.charting/components/charts/CustomChart.min.js?v=@@timestamp",
	WidgetChart : "build-config/build/bizviz.charting/components/charts/WidgetChart.min.js?v=@@timestamp",
	DecisionTreeChart: "build-config/build/bizviz.charting/components/charts/DecisionTreeChart.min.js?v=@@timestamp",
	DecompositionChart: "build-config/build/bizviz.charting/components/charts/DecompositionChart.min.js?v=@@timestamp",
	GroupBarChart : "build-config/build/bizviz.charting/components/charts/GroupBarChart.min.js?v=@@timestamp",
	GroupColumnChart : "build-config/build/bizviz.charting/components/charts/GroupColumnChart.min.js?v=@@timestamp",
	HeatMapChart : "build-config/build/bizviz.charting/components/charts/HeatMapChart.min.js?v=@@timestamp",
	HistogramChart : "build-config/build/bizviz.charting/components/charts/HistogramChart.min.js?v=@@timestamp",
	KnowledgeGraphChart : "build-config/build/bizviz.charting/components/charts/KnowledgeGraphChart.min.js?v=@@timestamp",
	KPITile : "build-config/build/bizviz.charting/components/charts/KPITile.min.js?v=@@timestamp",
	LineChart : "build-config/build/bizviz.charting/components/charts/LineChart.min.js?v=@@timestamp",
	MitoPlotChart : "build-config/build/bizviz.charting/components/charts/MitoPlotChart.min.js?v=@@timestamp",
	MixedChart : "build-config/build/bizviz.charting/components/charts/MixedChart.min.js?v=@@timestamp",
	PieChart : "build-config/build/bizviz.charting/components/charts/PieChart.min.js?v=@@timestamp",
	ProgressChart : "build-config/build/bizviz.charting/components/charts/ProgressChart.min.js?v=@@timestamp",
	ProjectTimelineChart : "build-config/build/bizviz.charting/components/charts/ProjectTimelineChart.min.js?v=@@timestamp",
	ScatteredPlotChart : "build-config/build/bizviz.charting/components/charts/ScatteredPlotChart.min.js?v=@@timestamp",
	SentimentPlotChart : "build-config/build/bizviz.charting/components/charts/SentimentPlotChart.min.js?v=@@timestamp",
	SparkLineChart : "build-config/build/bizviz.charting/components/charts/SparkLineChart.min.js?v=@@timestamp",
	SpiderChart : "build-config/build/bizviz.charting/components/charts/SpiderChart.min.js?v=@@timestamp",
	SankeyChart : "build-config/build/bizviz.charting/components/charts/SankeyChart.min.js?v=@@timestamp",
	TimelineChart : "build-config/build/bizviz.charting/components/charts/TimelineChart.min.js?v=@@timestamp",
	TreeMapChart : "build-config/build/bizviz.charting/components/charts/TreeMapChart.min.js?v=@@timestamp",
	TrellisChart : "build-config/build/bizviz.charting/components/charts/TrellisChart.min.js?v=@@timestamp",
	WaterfallChart : "build-config/build/bizviz.charting/components/charts/WaterfallChart.min.js?v=@@timestamp",
	WordCloudChart : "build-config/build/bizviz.charting/components/charts/WordCloudChart.min.js?v=@@timestamp",
	NewWordCloudChart : "build-config/build/bizviz.charting/components/charts/NewWordCloudChart.min.js?v=@@timestamp",
	WorldMapChart : "build-config/build/bizviz.charting/components/maps/WorldMapChart.min.js?v=@@timestamp",

	SimpleFunnelChart : "build-config/build/bizviz.charting/components/charts/SimpleFunnelChart.min.js?v=@@timestamp",
	InvertedFunnelChart : "build-config/build/bizviz.charting/components/charts/InvertedFunnelChart.min.js?v=@@timestamp",
	PyramidChart : "build-config/build/bizviz.charting/components/charts/PyramidChart.min.js?v=@@timestamp",

	Rectangle : "build-config/build/bizviz.charting/components/container/Rectangle.min.js?v=@@timestamp",
	
	DynamicDataGrid : "build-config/build/bizviz.charting/components/datagrids/DynamicDataGrid.min.js?v=@@timestamp",
	SimpleDataGrid : "build-config/build/bizviz.charting/components/datagrids/SimpleDataGrid.min.js?v=@@timestamp",
	PagingDataGrid : "build-config/build/bizviz.charting/components/datagrids/PagingDataGrid.min.js?v=@@timestamp",
	TreeGrid : "build-config/build/bizviz.charting/components/datagrids/TreeGrid.min.js?v=@@timestamp",
	ScoreCard : "build-config/build/bizviz.charting/components/datagrids/TreeGrid.min.js?v=@@timestamp",
	JExcelDataGrid : "build-config/build/bizviz.charting/components/datagrids/JExcelDataGrid.min.js?v=@@timestamp",

	CheckboxFilter : "build-config/build/bizviz.charting/components/filters/CheckboxFilter.min.js?v=@@timestamp",
	ComboFilter : "build-config/build/bizviz.charting/components/filters/ComboFilter.min.js?v=@@timestamp",
	HierarchicalCombo : "build-config/build/bizviz.charting/components/filters/HierarchicalCombo.min.js?v=@@timestamp",
	ListFilter : "build-config/build/bizviz.charting/components/filters/ListFilter.min.js?v=@@timestamp",
	RadioFilter : "build-config/build/bizviz.charting/components/filters/RadioFilter.min.js?v=@@timestamp",

	ExportToPPTButton :"build-config/build/bizviz.charting/components/buttons/ExportToPPTButton.min.js?v=@@timestamp",
	FilterSaver :"build-config/build/bizviz.charting/components/buttons/FilterSaver.min.js?v=@@timestamp",
	Bullet : "build-config/build/bizviz.charting/components/singleValuedComponent/Bullet.min.js?v=@@timestamp",
	DataSearch : "build-config/build/bizviz.charting/components/singleValuedComponent/DataSearch.min.js?v=@@timestamp",
	DatePicker : "build-config/build/bizviz.charting/components/singleValuedComponent/DatePicker.min.js?v=@@timestamp",
	Gauge : "build-config/build/bizviz.charting/components/singleValuedComponent/Gauge.min.js?v=@@timestamp",
	GuidedTour : "build-config/build/bizviz.charting/components/singleValuedComponent/GuidedTour.min.js?v=@@timestamp",
	HSlider : "build-config/build/bizviz.charting/components/singleValuedComponent/HSlider.min.js?v=@@timestamp",
	ImageComponent : "build-config/build/bizviz.charting/components/singleValuedComponent/ImageComponent.min.js?v=@@timestamp",
	InfoButton : "build-config/build/bizviz.charting/components/singleValuedComponent/InfoButton.min.js?v=@@timestamp",
	Label : "build-config/build/bizviz.charting/components/singleValuedComponent/Label.min.js?v=@@timestamp",
	Legend : "build-config/build/bizviz.charting/components/singleValuedComponent/Legend.min.js?v=@@timestamp",
	NumericStepper : "build-config/build/bizviz.charting/components/singleValuedComponent/NumericStepper.min.js?v=@@timestamp",
	SemiGauge : "build-config/build/bizviz.charting/components/singleValuedComponent/SemiGauge.min.js?v=@@timestamp",
	SVGImage : "build-config/build/bizviz.charting/components/singleValuedComponent/SVGImage.min.js?v=@@timestamp",
	SVGShape : "build-config/build/bizviz.charting/components/singleValuedComponent/SVGShape.min.js?v=@@timestamp",
	TextBox : "build-config/build/bizviz.charting/components/singleValuedComponent/TextBox.min.js?v=@@timestamp",
	InputBox : "build-config/build/bizviz.charting/components/singleValuedComponent/InputBox.min.js?v=@@timestamp",
	Trend : "build-config/build/bizviz.charting/components/singleValuedComponent/Trend.min.js?v=@@timestamp",
	UrlButton : "build-config/build/bizviz.charting/components/singleValuedComponent/UrlButton.min.js?v=@@timestamp",
	InputButton : "build-config/build/bizviz.charting/components/singleValuedComponent/InputButton.min.js?v=@@timestamp",
	TabComponent : "build-config/build/bizviz.charting/components/singleValuedComponent/TabComponent.min.js?v=@@timestamp",
	VSlider : "build-config/build/bizviz.charting/components/singleValuedComponent/VSlider.min.js?v=@@timestamp",
	FilterChips : "build-config/build/bizviz.charting/components/singleValuedComponent/FilterChips.min.js?v=@@timestamp"
};
dGlobals.src_url_dashboardhome = {};
dGlobals.src_url_dashboardhome.prodJS = [
	"build-config/build/bizviz.charting/chartingBase.min.js?v=@@timestamp",
	"build-config/build/bizviz.charting/components/buttons/ExportPlugin.min.js?v=@@timestamp",
	"build-config/build/bizviz.charting/components/buttons/ExportToPPTButton.min.js?v=@@timestamp",
	"build-config/build/bizviz.framework/chartingFramework.min.js?v=@@timestamp",
	"build-config/build/bizviz.ext/chartingSDK.min.js?v=@@timestamp"
];
dGlobals.src_url_dashboardhome.devJS = [
	"src/bizviz.charting/Widget.js?v=@@timestamp",
	"src/bizviz.charting/components/Chart.js?v=@@timestamp",
	"src/bizviz.charting/components/DataGrid.js?v=@@timestamp",
	"src/bizviz.charting/components/Filter.js?v=@@timestamp",
	"src/bizviz.charting/components/buttons/ExportPlugin.js?v=@@timestamp",
	"src/bizviz.charting/components/buttons/ExportToPPTButton.js?v=@@timestamp",
	"src/bizviz.framework/Parser.js?v=@@timestamp",
	"src/bizviz.framework/DataManager.js?v=@@timestamp",
	"src/bizviz.framework/ServiceManager.js?v=@@timestamp",
	"src/bizviz.framework/GlobalVariableController.js?v=@@timestamp",
	"src/bizviz.framework/RendererController.js?v=@@timestamp",
	"src/bizviz.framework/FrameworkController.js?v=@@timestamp",
	"src/bizviz.framework/FrameworkComponents.js?v=@@timestamp",
	"src/bdbizviz.ext/UserScriptExecuter.js?v=@@timestamp",
	"src/bdbizviz.ext/BizVizDesignUserSDK.js?v=@@timestamp"
];

dGlobals.src_url_preview = {};
dGlobals.src_url_preview.prodJS = [
	"../../charting/build-config/build/bizviz.charting/chartingBase.min.js?v=@@timestamp",
	"../../charting/build-config/build/bizviz.charting/components/buttons/ExportPlugin.min.js?v=@@timestamp",
	"../../charting/build-config/build/bizviz.charting/chartingComponents.min.js?v=@@timestamp",
	"../../charting/build-config/build/bizviz.framework/chartingFramework.min.js?v=@@timestamp",
	"../../charting/build-config/build/bizviz.ext/chartingSDK.min.js?v=@@timestamp"
];
dGlobals.src_url_preview.devJS = [
	"../../charting/src/bizviz.charting/Widget.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/Chart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/buttons/ExportPlugin.js?v=@@timestamp",
		
	"../../charting/src/bizviz.charting/components/buttons/ExportToPPTButton.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/buttons/FilterSaver.js?v=@@timestamp",
	
	"../../charting/src/bizviz.charting/components/charts/AreaChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/BarChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/BenchmarkAnalysisChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/BubbleChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/BoxPlotChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/CandleStickChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/ChevronChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/CircumplexChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/ColumnStackChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/CustomChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/WidgetChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/DecisionTreeChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/DecompositionChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/GroupBarChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/GroupColumnChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/HeatMapChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/HistogramChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/InvertedFunnelChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/KnowledgeGraphChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/KPITile.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/LineChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/MitoPlotChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/MixedChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/PieChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/ProgressChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/ProjectTimelineChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/PyramidChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/RoadMapChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/ScatteredPlotChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/SentimentPlotChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/SimpleFunnelChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/SparkLineChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/SpiderChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/SankeyChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/TimelineChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/TimeAreaChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/TimeColumnStackChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/TreeMapChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/TrellisChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/WaterfallChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/WordCloudChart.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/charts/NewWordCloudChart.js?v=@@timestamp",
		
	"../../charting/src/bizviz.charting/components/container/Rectangle.js?v=@@timestamp",

	"../../charting/src/bizviz.charting/components/DataGrid.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/datagrids/DynamicDataGrid.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/datagrids/SimpleDataGrid.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/datagrids/PagingDataGrid.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/datagrids/TreeGrid.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/datagrids/JExcelDataGrid.js?v=@@timestamp",
		
	"../../charting/src/bizviz.charting/components/Filter.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/filters/CheckboxFilter.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/filters/ComboFilter.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/filters/HierarchicalCombo.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/filters/ListFilter.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/filters/MultiSelectComboFilter.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/filters/RadioFilter.js?v=@@timestamp",
			
	"../../charting/src/bizviz.charting/components/maps/WorldMapChart.js?v=@@timestamp",
		
	"../../charting/src/bizviz.charting/components/singleValuedComponent/Bullet.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/CheckList.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/DataSearch.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/DatePicker.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/Gauge.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/GuidedTour.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/HSlider.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/ImageComponent.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/InfoButton.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/Label.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/Legend.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/NumericStepper.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/SemiGauge.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/SVGImage.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/SVGShape.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/TextBox.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/InputBox.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/Trend.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/UrlButton.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/InputButton.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/TabComponent.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/VSlider.js?v=@@timestamp",
	"../../charting/src/bizviz.charting/components/singleValuedComponent/FilterChips.js?v=@@timestamp",
		
	"../../charting/src/bizviz.framework/Parser.js?v=@@timestamp",
	"../../charting/src/bizviz.framework/DataManager.js?v=@@timestamp",
	"../../charting/src/bizviz.framework/ServiceManager.js?v=@@timestamp",
	"../../charting/src/bizviz.framework/GlobalVariableController.js?v=@@timestamp",
	"../../charting/src/bizviz.framework/RendererController.js?v=@@timestamp",
	"../../charting/src/bizviz.framework/FrameworkController.js?v=@@timestamp",
	"../../charting/src/bizviz.framework/FrameworkComponents.js?v=@@timestamp",
		
	"../../charting/src/bdbizviz.ext/UserScriptExecuter.js?v=@@timestamp",
	"../../charting/src/bdbizviz.ext/BizVizDesignUserSDK.js?v=@@timestamp"
];
dGlobals.src_url_pluginDependency_JS = {
	WorldMapChart: ["src/bizviz.charting/components/resources/js/leaflet-src.min.js?v=@@timestamp",
		"src/bizviz.charting/components/resources/js/leaflet.provider.min.js?v=@@timestamp",
		"src/bizviz.charting/components/resources/js/Leaflet.MakiMarkers.min.js?v=@@timestamp",
		"src/bizviz.charting/components/resources/js/leaflet.markercluster-src.min.js?v=@@timestamp"],
	ProjectTimelineChart: ["src/bizviz.charting/components/resources/js/visTimeline.min.js?v=@@timestamp"],
	KnowledgeGraphChart: ["src/bizviz.charting/components/resources/js/visNetwork.min.js?v=@@timestamp"],
	TreeMapChart: ["src/bizviz.charting/components/resources/js/jquery.ui.treemap.min.js?v=@@timestamp"],
	ListFilter: ["src/bizviz.charting/components/resources/js/jquery.listswap.min.js?v=@@timestamp"],
	JExcelDataGrid: ["src/bizviz.charting/components/resources/js/jexcel.js?v=@@timestamp",
		"src/bizviz.charting/components/resources/js/jsuites.js?v=@@timestamp"]
};
dGlobals.src_url_pluginDependency_CSS = {
	WorldMapChart: ["src/bizviz.charting/components/resources/css/leaflet.min.css?v=@@timestamp"],
	ProjectTimelineChart: ["src/bizviz.charting/components/resources/css/visTimeline.min.css?v=@@timestamp"],
	ListFilter: ["src/bizviz.charting/components/resources/css/listswap.min.css?v=@@timestamp"],
	JExcelDataGrid: ["src/bizviz.charting/components/resources/css/jexcel.css?v=@@timestamp",
		"src/bizviz.charting/components/resources/css/jsuites.css?v=@@timestamp"]
};

dGlobals.src_url_requiredPlugin_devJS = [
	"src/bizviz.charting/components/resources/js/jquery.sparkline.js?v=@@timestamp",
	"src/bizviz.charting/components/resources/js/svg.js?v=@@timestamp",
	"src/bizviz.charting/components/resources/js/sha256.js?v=@@timestamp",
	"src/bizviz.charting/components/resources/js/xml2json.js?v=@@timestamp"
];
dGlobals.src_url_requiredPlugin_prodJS = [
	"src/bizviz.charting/components/resources/js/jquery.sparkline.min.js?v=@@timestamp",
	"src/bizviz.charting/components/resources/js/svg.min.js?v=@@timestamp",
	"src/bizviz.charting/components/resources/js/sha256.min.js?v=@@timestamp",
	"src/bizviz.charting/components/resources/js/xml2json.min.js?v=@@timestamp"
];